'use client'

import { useActionState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Button } from '@/components/ui/button'
import type { CategoryFormState } from './actions'

function FieldError({ messages }: { messages?: string[] }) {
  if (!messages?.length) return null
  return <p className="text-xs text-destructive mt-1">{messages[0]}</p>
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

interface CategoryFormProps {
  siteId: string
  action: (prev: CategoryFormState, formData: FormData) => Promise<CategoryFormState>
  defaultValues?: {
    name?: string
    slug?: string
    description?: string
    seo_text?: string
    focus_keyword?: string
    keywords?: string[] | null
  }
  mode: 'create' | 'edit'
}

export function CategoryForm({ siteId, action, defaultValues, mode }: CategoryFormProps) {
  const router = useRouter()
  const [state, formAction, isPending] = useActionState<CategoryFormState, FormData>(action, null)

  useEffect(() => {
    if (state?.success) {
      router.push(`/sites/${siteId}#categories`)
      router.refresh()
    }
  }, [state?.success, router, siteId])

  const errors = state?.errors

  return (
    <form action={formAction} className="space-y-5">
      {/* Name + Slug */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="space-y-1.5">
          <Label htmlFor="name">
            Name <span className="text-destructive">*</span>
          </Label>
          <Input
            id="name"
            name="name"
            defaultValue={defaultValues?.name ?? ''}
            placeholder="Air Fryers"
            required
            aria-invalid={!!errors?.name}
            onChange={(e) => {
              if (mode === 'create') {
                const slugInput = document.getElementById('slug') as HTMLInputElement | null
                if (slugInput && !slugInput.dataset.touched) {
                  slugInput.value = slugify(e.target.value)
                }
              }
            }}
          />
          <FieldError messages={errors?.name} />
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="slug">
            Slug <span className="text-destructive">*</span>
          </Label>
          <Input
            id="slug"
            name="slug"
            defaultValue={defaultValues?.slug ?? ''}
            placeholder="air-fryers"
            required
            aria-invalid={!!errors?.slug}
            onInput={(e) => {
              ;(e.currentTarget as HTMLInputElement).dataset.touched = '1'
            }}
          />
          <FieldError messages={errors?.slug} />
        </div>
      </div>

      {/* Description */}
      <div className="space-y-1.5">
        <Label htmlFor="description">Description</Label>
        <Textarea
          id="description"
          name="description"
          defaultValue={defaultValues?.description ?? ''}
          placeholder="Short description of this category"
          rows={2}
        />
      </div>

      {/* Focus keyword */}
      <div className="space-y-1.5">
        <Label htmlFor="focus_keyword">Focus Keyword</Label>
        <Input
          id="focus_keyword"
          name="focus_keyword"
          defaultValue={defaultValues?.focus_keyword ?? ''}
          placeholder="best air fryers"
        />
        <p className="text-xs text-muted-foreground">Main SEO keyword for this category page.</p>
      </div>

      {/* Keywords */}
      <div className="space-y-1.5">
        <Label htmlFor="keywords">Keywords</Label>
        <Input
          id="keywords"
          name="keywords"
          defaultValue={defaultValues?.keywords?.join(', ') ?? ''}
          placeholder="air fryer, freidora de aire, hot air fryer"
        />
        <p className="text-xs text-muted-foreground">Comma-separated list of related keywords.</p>
      </div>

      {/* SEO text */}
      <div className="space-y-1.5">
        <Label htmlFor="seo_text">SEO Text</Label>
        <Textarea
          id="seo_text"
          name="seo_text"
          defaultValue={defaultValues?.seo_text ?? ''}
          placeholder="~400-word SEO text for this category page. Will be generated by AI if left empty."
          rows={8}
        />
      </div>

      {/* Form-level error */}
      {errors?._form && (
        <div className="rounded-lg border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">
          {errors._form[0]}
        </div>
      )}

      <div className="flex items-center gap-3">
        <Button type="submit" disabled={isPending}>
          {isPending ? 'Saving…' : mode === 'create' ? 'Create Category' : 'Save Changes'}
        </Button>
        <Link
          href={`/sites/${siteId}#categories`}
          className="text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          Cancel
        </Link>
      </div>
    </form>
  )
}
