-- Add optimized_title to tsa_products.
-- Stores the SEO-optimized product title (50-80 chars) generated by the SEO content job.
-- Format: [Brand] [Product] [Feature] — [Differentiator], in the site language.
-- Null = not yet generated; templates fall back to the raw Amazon title.

ALTER TABLE tsa_products
  ADD COLUMN IF NOT EXISTS optimized_title text DEFAULT NULL;

COMMENT ON COLUMN tsa_products.optimized_title IS 'SEO-optimized product title (50-80 chars) generated by ContentGenerator. Null = not yet generated; templates fall back to the raw Amazon title.';
