-- Add meta_description to tsa_categories
-- Used by the Astro generator to render <meta name="description"> on category pages.
-- Generated by the SEO content agent alongside focus_keyword, description, and seo_text.

ALTER TABLE tsa_categories
  ADD COLUMN IF NOT EXISTS meta_description TEXT;

COMMENT ON COLUMN tsa_categories.meta_description IS
  'Category page meta description (140-155 chars). Generated by the SEO content agent.';
